title: AI for Space
email: bo.chen@adelaide.edu.au
description: Website for Artificial Intelligence for Space
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
